countries_dict = {
  'SE': ['Sweden', 2, 2],
  'IT': ['Italy', 7, 8],
  'RS': ['Serbia', 1, 1],
  'NL': ['The Netherlands', 4, 4],
  'XK': ['Kosovo', 2, 2],
  'EE': ['Estonia', 2, 2],
  'BE': ['Belgium', 2, 3],
  'GR': ['Greece', 2, 2],
  'ES': ['Spain', 2, 2],
  'PT': ['Portugal', 1, 1],
  'FO': ['Faroe Islands', 6, 6],
  'NP': ['Nepal', 21, 28],
  'JE': ['Jersey', 1, 1],
  'ME': ['Montenegro', 1, 1],
  'MY': ['Malaysia', 5, 5],
  'BZ': ['Belize', 1, 1],
  'TH': ['Thailand', 4, 4],
  'MA': ['Morocco', 4, 4],
  'IE': ['Ireland', 7, 7],
  'RU': ['Russia', 5, 5],
  'HR': ['Croatia', 3, 9],
  'SG': ['Singapore', 5, 6],
  'CN': ['South China Sea Islands (disputed)', 15, 18],
  'CH': ['Switzerland', 2, 2],
  'BS': ['Bahamas', 1, 1],
  'BA': ['Bosnia and Herzegovina', 3, 3],
  'MC': ['Monaco', 2, 2],
  'DE': ['Germany', 21, 24],
  'GL': ['Greenland', 1, 1],
  'DK': ['Denmark', 4, 4],
  'CA': ['Canada', 239, 311],
  'ID': ['Indonesia', 9, 10],
  'VN': ['Vietnam', 1, 1],
  'US': ['United States of America', 99, 109],
  'FR': ['France', 19, 21],
  'IS': ['Iceland', 1, 1],
  'GB': ['United Kingdom', 320, 570],
  'FI': ['Finland', 5, 5],
  'NO': ['Norway', 2, 2],
  'IN': ['India', 2, 4]
}
