countries_dict = {
  'BS': ['The Bahamas', 1, 23],
  'ES': ['Spain', 9, 36],
  'US': ['United States of America', 61, 198],
  'CN': ['South China Sea Islands (disputed)', 4, 6],
  'CH': ['Switzerland', 11, 32],
  'BE': ['Belgium', 5, 8],
  'PA': ['Panama', 1, 1],
  'ME': ['Montenegro', 1, 1],
  'NL': ['Netherlands', 12, 59],
  'KR': ['South Korea', 1, 1],
  'DK': ['Denmark', 2, 2],
  'CA': ['Canada', 9, 37],
  'AU': ['Australia', 1, 1],
  'AD': ['Andorra', 1, 1],
  'DE': ['Germany', 361, 1254],
  'HR': ['Croatia', 41, 208],
  'CU': ['Cuba', 1, 1],
  'IE': ['Ireland', 2, 12],
  'AT': ['Austria', 10, 25],
  'IT': ['Italy', 108, 380],
  'MT': ['Malta', 1, 1],
  'GB': ['United Kingdom', 66, 152],
  'NO': ['Norway', 1, 1],
  'SI': ['Slovenia', 3, 42],
  'GR': ['Greece', 1, 1],
  'PT': ['Portugal', 2, 2],
  'BM': ['Bermuda', 1, 1],
  'PL': ['Poland', 2, 2],
  'MX': ['Mexico', 2, 2],
  'FR': ['France', 17, 23],
  'LU': ['Luxembourg', 3, 13],
  'CZ': ['Czechia', 1, 1],
  'SE': ['Sweden', 1, 6],
  'UA': ['Ukraine', 1, 1],
  'MC': ['Monaco', 1, 1]
}
