countries_dict = {
  'CN': ['South China Sea Islands (disputed)', 1, 1],
  'BR': ['Brazil', 4, 5],
  'NL': ['Netherlands', 2, 2],
  'GA': ['Gabon', 1, 1],
  'RU': ['Russia', 1, 1],
  'JO': ['Jordan', 1, 1],
  'SD': ['Sudan', 1, 1],
  'GB': ['United Kingdom', 5, 8],
  'FR': ['France', 2, 2],
  'EG': ['Egypt', 1, 1],
  'GR': ['Greece', 100, 115],
  'IT': ['Italy', 4, 4],
  'AD': ['Andorra', 1, 1],
  'SA': ['Saudi Arabia', 1, 1],
  'DE': ['Germany', 1, 1],
  'LB': ['Lebanon', 3, 3],
  'BE': ['Belgium', 1, 1],
  'TN': ['Tunisia', 1, 1],
  'TH': ['Thailand', 2, 3],
  'CH': ['Switzerland', 1, 1],
  'KI': ['Kiribati', 3, 3],
  'ES': ['Spain', 6, 8],
  'IN': ['India', 4, 592],
  'RS': ['Serbia', 1, 1],
  'US': ['United States of America', 19, 24]
}
