countries_dict = {
  'UZ': ['Uzbekistan', 1, 1],
  'ES': ['Spain', 1, 1],
  'NL': ['Netherlands', 1, 1],
  'FR': ['France', 8, 42],
  'EG': ['Egypt', 1, 1],
  'DE': ['Germany', 3, 3],
  'JP': ['Japan', 3, 3],
  'CH': ['Switzerland', 2, 2],
  'GB': ['United Kingdom', 5, 8],
  'LY': ['Libya', 1, 1],
  'AT': ['Austria', 1, 1],
  'EC': ['Ecuador', 1, 1],
  'HR': ['Croatia', 1, 1],
  'GR': ['Greece', 27, 39],
  'RO': ['Romania', 1, 1],
  'SE': ['Sweden', 1, 1],
  'CZ': ['Czechia', 2, 2],
  'TJ': ['Tajikistan', 1, 1],
  'CA': ['Canada', 1, 1],
  'IT': ['Italy', 12, 12],
  'HU': ['Hungary', 1, 3],
  'KW': ['Kuwait', 1, 1],
  'US': ['United States of America', 15, 15],
  'SK': ['Slovakia', 1, 1]
}
